title: Dinithi Gunawardena # your name (or website title) here
logo: "images/tuxpi.com.1679851067.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mobile : +9471329027
  Email : <a href = "dinithi.20210465@iit.ac.lk">dinithi.20210465@iit.ac.lk</a>
  <br><br>
  <a href="https://lk.linkedin.com/in/dinithi-gunawardena-7719a9164">View My LinkedIn Profile</a>  

theme: jekyll-theme-minimal
