title: Dinithi Gunawardena | Software Engineer
logo: ""
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Engineer & Data Science Enthusiast
  <br><br>
  BSc in Computer Science
  <br>
  University of Westminster - IIT Sri Lanka
  <br><br>
  <a href="mailto:dinithi.20210465@iit.ac.lk">dinithi.20210465@iit.ac.lk</a>
  <br>
  <a href="tel:+94713249027">+94 71 324 9027</a>
  <br><br>
  <a href="https://lk.linkedin.com/in/dinithi-gunawardena-7719a9164" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn Profile</a>
  <br>
  <a href="https://github.com/DinithiG" target="_blank"><i class="fab fa-github"></i> GitHub Profile</a>

# Social media links (uncomment as needed)
social_links:
  linkedin: dinithi-gunawardena-7719a9164
  github: DinithiG
  # twitter: your-username
  # facebook: your-username

# Google Analytics (if you have a tracking ID)
# google_analytics: UA-XXXXXXXXX-X

theme: jekyll-theme-minimal
