title: Dinithi Gunawardena # your name (or website title) here
logo: "images/tuxpi.com.1679851067.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  I’m a computer science undergraduate with a passion for data science and business analytics.
  I'm looking for more opportunities to improve myself and develop professionally.
  <br>
  <a href="https://lk.linkedin.com/in/dinithi-gunawardena-7719a9164">View My LinkedIn Profile</a>  

theme: jekyll-theme-minimal
